# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 460)
        Form.setStyleSheet("background-color: #A0B9D0;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("#output_txt{\n"
"    border-radius:8px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.output_txt = QtWidgets.QTextEdit(self.frame)
        self.output_txt.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.output_txt.setFont(font)
        self.output_txt.setStyleSheet("background-color:#335E81;\n"
"color: #B0C3D7;\n"
"padding-left:5px;\n"
"padding-right:5px;\n"
"padding-top:5px;")
        self.output_txt.setLineWidth(1)
        self.output_txt.setObjectName("output_txt")
        self.verticalLayout_3.addWidget(self.output_txt)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("#input_txt{\n"
"    border-radius: 8px;\n"
"    background-color:#335E81;\n"
"    color: #B0C3D7;    \n"
"    padding-left: 5px;\n"
"    padding-right:5px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_txt = QtWidgets.QLineEdit(self.frame_2)
        self.input_txt.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(12)
        self.input_txt.setFont(font)
        self.input_txt.setObjectName("input_txt")
        self.verticalLayout_2.addWidget(self.input_txt)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_txt.setPlaceholderText(_translate("Form", "Command"))

from static import res_rc
