# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Loginview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1353, 700)
        Form.setStyleSheet("/*Set style for app title widget*/\n"
"#titleWidget{\n"
"    background-image: url(:/Img/img/final1.jpg);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-top-left-radius: 20px;\n"
"}\n"
"\n"
"#titleWidget QLabel{\n"
"    color: #A7BED3;\n"
"    font-family: \"Stencil\"\n"
"}\n"
"\n"
"#titleLabel1{\n"
"    font-size: 35px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/*Set style for function widget*/\n"
"#funcWidget {\n"
"    background-image: url(:/Img/img/123.jpg);\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top: 2px soild #343434;\n"
"    border-right: 2px soild #343434;\n"
"    border-bottom: 2px soild #343434;\n"
"}\n"
"\n"
"/*Set style for login label and register label in function widget*/\n"
"#LoginLabel, #RegisLabel{\n"
"    color: #A7BED3;\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/*Set style for all the QLabel in function widget*/\n"
"#funcWidget QLabel{\n"
"    color: #A7BED3;\n"
"    font-family: \"Stencil\";\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/*Set style for all the buttons in function widget*/\n"
"#funcWidget QLineEdit{\n"
"    border: 1px soild #E4E6C3;\n"
"    padding: 5px 10px;\n"
"    background-color: #F7F7F2 ;\n"
"    font-size:15px;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"#funcWidget QLineEdit:focus{\n"
"    border-color: #F7F7F2\n"
"}\n"
"\n"
"/*Set style for all the buttons in function widget*/\n"
"#funcWidget QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color:#CBCBCD\n"
"}\n"
"\n"
"#funcWidget QPushButton:pressed{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"/*Set style for long and creat device button in function widget */\n"
"#LoginButton:hover, #LoginButton:pressed, #AddButton:hover, #AddButton:pressed{\n"
"    background-color: #00A8B8;\n"
"}\n"
"#CreateButton:hover, #CreateButton:pressed{\n"
"    background-color: #00CC9C;\n"
"}\n"
"#ExitButton:hover, #ExitButton:pressed{\n"
"    background-color: #FF7733;\n"
"}\n"
"#BackButton:hover, #BackButton:pressed{\n"
"    background-color: #00B4F5;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(58, 688, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 2, 1)
        self.titleWidget = QtWidgets.QWidget(Form)
        self.titleWidget.setMinimumSize(QtCore.QSize(700, 500))
        self.titleWidget.setMaximumSize(QtCore.QSize(700, 500))
        self.titleWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleWidget.setStyleSheet("")
        self.titleWidget.setObjectName("titleWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 213, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 25)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel1 = QtWidgets.QLabel(self.titleWidget)
        self.titleLabel1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel1.setObjectName("titleLabel1")
        self.verticalLayout.addWidget(self.titleLabel1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 213, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.titleWidget, 0, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(58, 688, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 2, 1)
        self.funcWidget = QtWidgets.QStackedWidget(Form)
        self.funcWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.funcWidget.setMaximumSize(QtCore.QSize(500, 500))
        self.funcWidget.setObjectName("funcWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RegisLabel = QtWidgets.QLabel(self.page)
        self.RegisLabel.setStyleSheet("#RegisLabel{\n"
"    color: #1A3551;\n"
"    font-size: 30px;\n"
"}")
        self.RegisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RegisLabel.setObjectName("RegisLabel")
        self.verticalLayout_6.addWidget(self.RegisLabel)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.NameLabel2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(-1)
        font.setBold(True)
        self.NameLabel2.setFont(font)
        self.NameLabel2.setObjectName("NameLabel2")
        self.verticalLayout_7.addWidget(self.NameLabel2)
        self.NameDevice2 = QtWidgets.QLineEdit(self.page)
        self.NameDevice2.setClearButtonEnabled(True)
        self.NameDevice2.setObjectName("NameDevice2")
        self.verticalLayout_7.addWidget(self.NameDevice2)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.IPLabel2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(-1)
        font.setBold(True)
        self.IPLabel2.setFont(font)
        self.IPLabel2.setObjectName("IPLabel2")
        self.verticalLayout_8.addWidget(self.IPLabel2)
        self.IPDevice2 = QtWidgets.QLineEdit(self.page)
        self.IPDevice2.setClearButtonEnabled(True)
        self.IPDevice2.setObjectName("IPDevice2")
        self.verticalLayout_8.addWidget(self.IPDevice2)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BackButton = QtWidgets.QPushButton(self.page)
        self.BackButton.setMinimumSize(QtCore.QSize(161, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Img/icons/reply-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon)
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout_2.addWidget(self.BackButton)
        self.AddButton = QtWidgets.QPushButton(self.page)
        self.AddButton.setMinimumSize(QtCore.QSize(160, 30))
        self.AddButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Img/icons/check-mark-3-16.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddButton.setIcon(icon1)
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout_2.addWidget(self.AddButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        self.funcWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LoginLabel = QtWidgets.QLabel(self.page_2)
        self.LoginLabel.setMinimumSize(QtCore.QSize(319, 60))
        self.LoginLabel.setStyleSheet("#LoginLabel{\n"
"    font-size: 30px;\n"
"    color: #1A3551\n"
"}")
        self.LoginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.verticalLayout_5.addWidget(self.LoginLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.NameLabel1 = QtWidgets.QLabel(self.page_2)
        self.NameLabel1.setMinimumSize(QtCore.QSize(317, 30))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(-1)
        font.setBold(True)
        self.NameLabel1.setFont(font)
        self.NameLabel1.setObjectName("NameLabel1")
        self.verticalLayout_3.addWidget(self.NameLabel1)
        self.NameDevice1 = QtWidgets.QLineEdit(self.page_2)
        self.NameDevice1.setMinimumSize(QtCore.QSize(317, 22))
        self.NameDevice1.setClearButtonEnabled(True)
        self.NameDevice1.setObjectName("NameDevice1")
        self.verticalLayout_3.addWidget(self.NameDevice1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IPLabel1 = QtWidgets.QLabel(self.page_2)
        self.IPLabel1.setMinimumSize(QtCore.QSize(317, 29))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(-1)
        font.setBold(True)
        self.IPLabel1.setFont(font)
        self.IPLabel1.setObjectName("IPLabel1")
        self.verticalLayout_4.addWidget(self.IPLabel1)
        self.IPDevice1 = QtWidgets.QLineEdit(self.page_2)
        self.IPDevice1.setMinimumSize(QtCore.QSize(317, 22))
        self.IPDevice1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.IPDevice1.setClearButtonEnabled(True)
        self.IPDevice1.setObjectName("IPDevice1")
        self.verticalLayout_4.addWidget(self.IPDevice1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExitButton = QtWidgets.QPushButton(self.page_2)
        self.ExitButton.setMinimumSize(QtCore.QSize(102, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Img/icons/close_10263254.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitButton.setIcon(icon2)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout.addWidget(self.ExitButton)
        self.CreateButton = QtWidgets.QPushButton(self.page_2)
        self.CreateButton.setMinimumSize(QtCore.QSize(101, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Img/icons/laptop-medical-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CreateButton.setIcon(icon3)
        self.CreateButton.setObjectName("CreateButton")
        self.horizontalLayout.addWidget(self.CreateButton)
        self.LoginButton = QtWidgets.QPushButton(self.page_2)
        self.LoginButton.setMinimumSize(QtCore.QSize(102, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Img/icons/arrow-right-to-bracket-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoginButton.setIcon(icon4)
        self.LoginButton.setObjectName("LoginButton")
        self.horizontalLayout.addWidget(self.LoginButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 2, 1, 1, 1)
        self.funcWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.funcWidget, 0, 2, 2, 1)

        self.retranslateUi(Form)
        self.funcWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel1.setText(_translate("Form", "RASPBERRY APPLICATION"))
        self.RegisLabel.setText(_translate("Form", "Add Device"))
        self.NameLabel2.setText(_translate("Form", "Name device:"))
        self.IPLabel2.setText(_translate("Form", "Address IP:"))
        self.BackButton.setText(_translate("Form", "Back"))
        self.AddButton.setText(_translate("Form", "Add device"))
        self.LoginLabel.setText(_translate("Form", "Connect"))
        self.NameLabel1.setText(_translate("Form", "Address IP"))
        self.IPLabel1.setText(_translate("Form", "Port"))
        self.ExitButton.setText(_translate("Form", "Exit"))
        self.CreateButton.setText(_translate("Form", "Add"))
        self.LoginButton.setText(_translate("Form", "Connect"))
from static import resource_rc
