# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 640)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: #4B7C9B;\n"
"}\n"
"#centralwidget QPushButton{\n"
"    width:100px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 3px;\n"
"    font-weight:bold;\n"
"    border-radius:10px;\n"
"    color: #11253E;\n"
"    border: 1px;\n"
"}\n"
"#centralwidget QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#centralwidget QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    background-color:#78A0BC;\n"
"}\n"
"\n"
"#footer_widget{\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"#splitter{\n"
"    border-radius:10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.footer_widget = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.footer_widget.setFont(font)
        self.footer_widget.setStyleSheet("#QPushButton{\n"
"    width:100px;\n"
"    height:33px;\n"
"    text-align: center;\n"
"    padding: 5px 20px 5px 20px;\n"
"    padding: 10px;\n"
"\n"
"    font-weight:bold;\n"
"    border-radius:20px;\n"
"    color: #11253E;\n"
"    border: 1px;\n"
"}\n"
"#QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#QPushButton:checked{\n"
"    background-color:#78A0BC;\n"
"}")
        self.footer_widget.setObjectName("footer_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.footer_widget)
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_footer_frame = QtWidgets.QFrame(self.footer_widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.left_footer_frame.setFont(font)
        self.left_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_frame.setObjectName("left_footer_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.left_footer_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shutdown_btn = QtWidgets.QPushButton(self.left_footer_frame)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.shutdown_btn.setFont(font)
        self.shutdown_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shutdown_btn.setStyleSheet("#QPushButton{\n"
"    background-color: #8DAEC6;\n"
"    font-weight:bold;\n"
"    border-radius: 20px\n"
"}\n"
"#QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#QPushButton:pressed{\n"
"    background-color:#78A0BC;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutdown_btn.setIcon(icon)
        self.shutdown_btn.setIconSize(QtCore.QSize(24, 24))
        self.shutdown_btn.setObjectName("shutdown_btn")
        self.horizontalLayout_2.addWidget(self.shutdown_btn)
        self.reboot_btn = QtWidgets.QPushButton(self.left_footer_frame)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.reboot_btn.setFont(font)
        self.reboot_btn.setTabletTracking(False)
        self.reboot_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reboot_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.reboot_btn.setAcceptDrops(False)
        self.reboot_btn.setToolTipDuration(-1)
        self.reboot_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reboot_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/refresh-ccw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reboot_btn.setIcon(icon1)
        self.reboot_btn.setIconSize(QtCore.QSize(24, 24))
        self.reboot_btn.setFlat(False)
        self.reboot_btn.setObjectName("reboot_btn")
        self.horizontalLayout_2.addWidget(self.reboot_btn)
        self.horizontalLayout_4.addWidget(self.left_footer_frame, 0, QtCore.Qt.AlignLeft)
        self.right_footer_frame = QtWidgets.QFrame(self.footer_widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.right_footer_frame.setFont(font)
        self.right_footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_footer_frame.setObjectName("right_footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.right_footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.disconnect_btn = QtWidgets.QPushButton(self.right_footer_frame)
        self.disconnect_btn.setMinimumSize(QtCore.QSize(141, 26))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.disconnect_btn.setFont(font)
        self.disconnect_btn.setStyleSheet("#QPushButton{\n"
"    background-color: #8DAEC6;\n"
"    font-weight:bold;\n"
"    border-radius: 20px;\n"
"}\n"
"#QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#QPushButton:checked{\n"
"    background-color:#78A0BC;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/cast.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disconnect_btn.setIcon(icon2)
        self.disconnect_btn.setIconSize(QtCore.QSize(24, 24))
        self.disconnect_btn.setObjectName("disconnect_btn")
        self.horizontalLayout_3.addWidget(self.disconnect_btn)
        self.horizontalLayout_4.addWidget(self.right_footer_frame, 0, QtCore.Qt.AlignRight)
        self.gridLayout_3.addWidget(self.footer_widget, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.splitter.setFont(font)
        self.splitter.setStyleSheet("#splitter{\n"
"    background-color: #C9D8E3;\n"
"}\n"
"\n"
"#menu_widget{\n"
"    border-top-left-radius: 10px;\n"
"}\n"
"\n"
"#main_widget{\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.menu_widget = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.menu_widget.setFont(font)
        self.menu_widget.setStyleSheet("background-color: #4B7C9B;\n"
"color: #0E243D;\n"
"\n"
"")
        self.menu_widget.setObjectName("menu_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_widget)
        self.gridLayout.setContentsMargins(15, 15, 10, 20)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(self.menu_widget)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(11)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("#toolBox{\n"
"    color:#8DAEC6;\n"
"    border-radius: 5%;\n"
"}\n"
"#toolBox::tab{\n"
"    padding-left:5px;\n"
"    text-align:left;\n"
"    border-radius:5px;\n"
"}\n"
"#toolBox::tab::hover{\n"
"    background-color:#82A7C2;\n"
"}\n"
"#toolBox::tab::selected{\n"
"    background-color:#8DAEC6;\n"
"    font-weight:bold;\n"
"}\n"
"#toolBox QPushButton{\n"
"    padding: 5px 0px 5px 20px;\n"
"    text-align:left;\n"
"    border-radius:5px;\n"
"    color: #11253E;\n"
"    border: 1px;\n"
"}\n"
"#toolBox QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#toolBox QPushButton:checked{\n"
"    background-color:#78A0BC;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.rasp_info_page = QtWidgets.QWidget()
        self.rasp_info_page.setGeometry(QtCore.QRect(0, 0, 236, 448))
        self.rasp_info_page.setObjectName("rasp_info_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rasp_info_page)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cpu_button = QtWidgets.QPushButton(self.rasp_info_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.cpu_button.setFont(font)
        self.cpu_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/cpu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cpu_button.setIcon(icon3)
        self.cpu_button.setIconSize(QtCore.QSize(24, 24))
        self.cpu_button.setCheckable(True)
        self.cpu_button.setChecked(False)
        self.cpu_button.setObjectName("cpu_button")
        self.verticalLayout.addWidget(self.cpu_button)
        self.sy_info_button = QtWidgets.QPushButton(self.rasp_info_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.sy_info_button.setFont(font)
        self.sy_info_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/monitor.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sy_info_button.setIcon(icon4)
        self.sy_info_button.setIconSize(QtCore.QSize(24, 24))
        self.sy_info_button.setCheckable(True)
        self.sy_info_button.setObjectName("sy_info_button")
        self.verticalLayout.addWidget(self.sy_info_button)
        self.os_info_button = QtWidgets.QPushButton(self.rasp_info_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.os_info_button.setFont(font)
        self.os_info_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/inbox.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.os_info_button.setIcon(icon5)
        self.os_info_button.setIconSize(QtCore.QSize(24, 24))
        self.os_info_button.setCheckable(True)
        self.os_info_button.setObjectName("os_info_button")
        self.verticalLayout.addWidget(self.os_info_button)
        spacerItem = QtWidgets.QSpacerItem(20, 414, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/hard-drive.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.rasp_info_page, icon6, "")
        self.activities_page = QtWidgets.QWidget()
        self.activities_page.setGeometry(QtCore.QRect(0, 0, 236, 448))
        self.activities_page.setObjectName("activities_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.activities_page)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.process_list_button = QtWidgets.QPushButton(self.activities_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.process_list_button.setFont(font)
        self.process_list_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.process_list_button.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.process_list_button.setIcon(icon7)
        self.process_list_button.setIconSize(QtCore.QSize(24, 24))
        self.process_list_button.setCheckable(True)
        self.process_list_button.setObjectName("process_list_button")
        self.verticalLayout_2.addWidget(self.process_list_button)
        self.file_list_button = QtWidgets.QPushButton(self.activities_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.file_list_button.setFont(font)
        self.file_list_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file_list_button.setIcon(icon8)
        self.file_list_button.setIconSize(QtCore.QSize(24, 24))
        self.file_list_button.setCheckable(True)
        self.file_list_button.setObjectName("file_list_button")
        self.verticalLayout_2.addWidget(self.file_list_button)
        self.terminal_button = QtWidgets.QPushButton(self.activities_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.terminal_button.setFont(font)
        self.terminal_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/terminal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terminal_button.setIcon(icon9)
        self.terminal_button.setIconSize(QtCore.QSize(24, 24))
        self.terminal_button.setCheckable(True)
        self.terminal_button.setObjectName("terminal_button")
        self.verticalLayout_2.addWidget(self.terminal_button)
        self.sftp_button = QtWidgets.QPushButton(self.activities_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.sftp_button.setFont(font)
        self.sftp_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/share-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sftp_button.setIcon(icon10)
        self.sftp_button.setIconSize(QtCore.QSize(24, 24))
        self.sftp_button.setCheckable(True)
        self.sftp_button.setObjectName("sftp_button")
        self.verticalLayout_2.addWidget(self.sftp_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 378, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/activity.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.activities_page, icon11, "")
        self.options_page = QtWidgets.QWidget()
        self.options_page.setGeometry(QtCore.QRect(0, 0, 236, 448))
        self.options_page.setObjectName("options_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.options_page)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.storage_button = QtWidgets.QPushButton(self.options_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.storage_button.setFont(font)
        self.storage_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/disc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.storage_button.setIcon(icon12)
        self.storage_button.setIconSize(QtCore.QSize(24, 24))
        self.storage_button.setCheckable(True)
        self.storage_button.setObjectName("storage_button")
        self.verticalLayout_3.addWidget(self.storage_button)
        self.network_button = QtWidgets.QPushButton(self.options_page)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.network_button.setFont(font)
        self.network_button.setFocusPolicy(QtCore.Qt.NoFocus)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/wifi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.network_button.setIcon(icon13)
        self.network_button.setIconSize(QtCore.QSize(24, 24))
        self.network_button.setCheckable(True)
        self.network_button.setObjectName("network_button")
        self.verticalLayout_3.addWidget(self.network_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 414, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-options-horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.options_page, icon14, "")
        self.gridLayout.addWidget(self.toolBox, 0, 1, 1, 1)
        self.main_widget = QtWidgets.QWidget(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setKerning(True)
        self.main_widget.setFont(font)
        self.main_widget.setToolTipDuration(-1)
        self.main_widget.setStyleSheet("#menu_widget{\n"
"    background-color: #A0B9D0;\n"
"}\n"
"#search_widget{\n"
"    border-top-right-radius: 10px;\n"
"}")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.search_widget = QtWidgets.QWidget(self.main_widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.search_widget.setFont(font)
        self.search_widget.setStyleSheet("#search_widget{\n"
"    background-color:#4B7C9B;\n"
"}\n"
"#search_widget QPushButton{\n"
"    border-radius: 5px;\n"
"    padding: 5px 20px 5px 20px;\n"
"    text-align:center;\n"
"}\n"
"#search_widge QPushButton:pressed{\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"/*Set style for long and creat device button in function widget */\n"
"")
        self.search_widget.setObjectName("search_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.search_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.header_frame = QtWidgets.QFrame(self.search_widget)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.header_frame.setFont(font)
        self.header_frame.setStyleSheet("#header_frame{\n"
"    background-color:none;\n"
"}\n"
"\n"
"#header_frame QPushButton{\n"
"    border-radius:5px;\n"
"    color: #11253E;\n"
"}\n"
"#header_frame QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#header_frame QPushButton:pressed{\n"
"    background-color:#78A0BC;\n"
"}")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_6.setContentsMargins(15, 8, 15, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menu_button = QtWidgets.QPushButton(self.header_frame)
        self.menu_button.setMinimumSize(QtCore.QSize(30, 30))
        self.menu_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.menu_button.setFont(font)
        self.menu_button.setMouseTracking(True)
        self.menu_button.setStyleSheet("#QPushButton{\n"
"    background-color: #8DAEC6;\n"
"    font-weight:bold;\n"
"    border-radius: 10%\n"
"}\n"
"#QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#QPushButton:checked{\n"
"    background-color:#78A0BC;\n"
"}")
        self.menu_button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/align-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_button.setIcon(icon15)
        self.menu_button.setIconSize(QtCore.QSize(24, 24))
        self.menu_button.setCheckable(True)
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_6.addWidget(self.menu_button)
        spacerItem3 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.center_header_frame = QtWidgets.QFrame(self.header_frame)
        self.center_header_frame.setMinimumSize(QtCore.QSize(331, 44))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.center_header_frame.setFont(font)
        self.center_header_frame.setStyleSheet("background-color:none;")
        self.center_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_header_frame.setObjectName("center_header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.center_header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.center_header_frame)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/feather/airplay.svg"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.center_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addWidget(self.center_header_frame)
        spacerItem4 = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.right_header_frame = QtWidgets.QFrame(self.header_frame)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.right_header_frame.setFont(font)
        self.right_header_frame.setStyleSheet("#right_header_frame{\n"
"    background-color:none;\n"
"}\n"
"# QPushButton:hover{\n"
"    background-color:#6991B5;\n"
"}\n"
"#QPushButton:checked{\n"
"    background-color:#78A0BC;\n"
"}")
        self.right_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_header_frame.setObjectName("right_header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.right_header_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minimize_window_btn = QtWidgets.QPushButton(self.right_header_frame)
        self.minimize_window_btn.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.minimize_window_btn.setFont(font)
        self.minimize_window_btn.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_btn.setIcon(icon16)
        self.minimize_window_btn.setIconSize(QtCore.QSize(24, 16))
        self.minimize_window_btn.setObjectName("minimize_window_btn")
        self.horizontalLayout_5.addWidget(self.minimize_window_btn)
        self.restore_window_btn = QtWidgets.QPushButton(self.right_header_frame)
        self.restore_window_btn.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.restore_window_btn.setFont(font)
        self.restore_window_btn.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_window_btn.setIcon(icon17)
        self.restore_window_btn.setObjectName("restore_window_btn")
        self.horizontalLayout_5.addWidget(self.restore_window_btn)
        self.close_window_btn = QtWidgets.QPushButton(self.right_header_frame)
        self.close_window_btn.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        font.setBold(True)
        self.close_window_btn.setFont(font)
        self.close_window_btn.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/newPrefix/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_btn.setIcon(icon18)
        self.close_window_btn.setObjectName("close_window_btn")
        self.horizontalLayout_5.addWidget(self.close_window_btn)
        self.horizontalLayout_6.addWidget(self.right_header_frame)
        self.verticalLayout_4.addWidget(self.header_frame)
        self.main_body_frame = QtWidgets.QFrame(self.search_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_frame.sizePolicy().hasHeightForWidth())
        self.main_body_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.main_body_frame.setFont(font)
        self.main_body_frame.setStyleSheet("background-color:#A0B9D0")
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_body_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.main_body_frame)
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setStyleSheet("#tabWidget{\n"
"    background-color: #A0B9D0;\n"
"    border-radius: 5px;\n"
"    border: 5px solid #A0B9D0;\n"
"}\n"
"\n"
"QTabBar::close-button{\n"
"    margin-left:3px;\n"
"    image: url(:/Img/icons/x-mark-4-16.ico);\n"
"}\n"
"QTabBar::close-button:hover{\n"
"    image: url(:/Img/icons/close_10263254.png);\n"
"}\n"
"QTabBar::tab{\n"
"    background-color:  #C9D8E3;\n"
"    min-width: 100px;\n"
"    max-width: 175px;\n"
"    height: 25px;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.main_body_frame)
        self.gridLayout_2.addWidget(self.search_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(-1)
        self.menu_button.toggled['bool'].connect(self.menu_widget.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.shutdown_btn.setText(_translate("MainWindow", " Shutdown"))
        self.reboot_btn.setText(_translate("MainWindow", " Reboot"))
        self.disconnect_btn.setText(_translate("MainWindow", " Disconnect"))
        self.cpu_button.setText(_translate("MainWindow", " CPU"))
        self.sy_info_button.setText(_translate("MainWindow", " System Information"))
        self.os_info_button.setText(_translate("MainWindow", " OS Information"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rasp_info_page), _translate("MainWindow", " Rasp Information"))
        self.process_list_button.setText(_translate("MainWindow", " Process List"))
        self.file_list_button.setText(_translate("MainWindow", " File List"))
        self.terminal_button.setText(_translate("MainWindow", " Terminal"))
        self.sftp_button.setText(_translate("MainWindow", " SFTP"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.activities_page), _translate("MainWindow", " Activities"))
        self.storage_button.setText(_translate("MainWindow", " Storage"))
        self.network_button.setText(_translate("MainWindow", " Network"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.options_page), _translate("MainWindow", " Options"))
        self.label_2.setText(_translate("MainWindow", "   RASBERRY PI APPLICATION"))
from static import res_rc
